spring:
  data:
    mongodb:
      host: mongodb
      port: 27017

server:
  ssl:
    enabled: true
    key-store-type: JKS
    key-store: classpath:keystore/key.p12
    key-alias: 1
    key-password: grace123
    key-store-password: grace123
    certificate: classpath:keystore/cert
  port: 8443