spring:
  data:
    mongodb:
      host: mongodb
      port: 27017

server:
  ssl:
    enabled: true
    key-store-type: JKS
    key-store: classpath:keystore/keystore.jks
    key-alias: server
    key-password: grace123
    key-store-password: grace123
  port: 443